const exerciseMedia = 'videos/';
const curatedMissions = [
  { id: 'bench', icon: '▣', title: 'DESPERTAR DEL PECHO', name: 'Barbell Bench Press', detail: '4 × 8 · +20 XP', xp: 120, target: 'Pectorales', secondary: ['Tríceps', 'Hombros'], equipment: 'Barra', category: 'PECHO', media: `${exerciseMedia}0025-EIeI8Vf.gif`, instructions: 'Acuéstate en el banco con los pies firmes en el suelo. Retrae las escápulas, baja la barra de forma controlada hasta el pecho medio y empuja hacia arriba sin perder la tensión.', cue: 'Mantén las muñecas rectas y los omóplatos juntos durante toda la serie.' },
  { id: 'pullup', icon: '↟', title: 'TRACCIÓN SOMBRÍA', name: 'Pull-up', detail: '3 × al fallo · +30 XP', xp: 150, target: 'Dorsales', secondary: ['Bíceps', 'Antebrazos'], equipment: 'Barra de dominadas', category: 'ESPALDA', media: `${exerciseMedia}0652-lBDjFxJ.gif`, instructions: 'Cuélgate de la barra de dominadas con las manos algo más abiertas que los hombros. Inicia el movimiento llevando los omóplatos hacia abajo y sube el pecho hacia la barra. Baja completamente con control.', cue: 'Evita balancearte: piensa en llevar los codos hacia las costillas.' },
  { id: 'deadlift', icon: '⌁', title: 'PIERNAS DE HIERRO', name: 'Barbell Deadlift', detail: '4 × 6 · +40 XP', xp: 180, target: 'Glúteos', secondary: ['Isquiosurales', 'Zona lumbar'], equipment: 'Barra', category: 'PIERNAS', media: `${exerciseMedia}0032-ila4NZS.gif`, instructions: 'Coloca la barra sobre el mediopié y toma el agarre justo fuera de las piernas. Activa el abdomen, empuja el suelo y extiende la cadera hasta quedar erguido, sin hiperextender la espalda.', cue: 'La barra debe viajar pegada a tus piernas; espalda neutra desde el inicio.' },
  { id: 'squat', icon: '⌂', title: 'TRONO DE ACERO', name: 'Barbell Full Squat', detail: '4 × 8 · +35 XP', xp: 160, target: 'Cuádriceps', secondary: ['Glúteos', 'Core'], equipment: 'Barra', category: 'PIERNAS', media: `${exerciseMedia}0043-qXTaZnJ.gif`, instructions: 'Apoya la barra sobre los trapecios, toma aire y desciende llevando las caderas hacia atrás hasta que los muslos pasen la paralela. Empuja con todo el pie para volver.', cue: 'Rodillas alineadas con los dedos de los pies y pecho alto.' },
  { id: 'curl', icon: '◒', title: 'NÚCLEO DEL BRAZO', name: 'Dumbbell Biceps Curl', detail: '3 × 12 · +25 XP', xp: 110, target: 'Bíceps', secondary: ['Antebrazos'], equipment: 'Mancuernas', category: 'BRAZOS', media: `${exerciseMedia}0294-NbVPDMW.gif`, instructions: 'Ponte de pie con los codos pegados al torso. Gira las palmas hacia arriba mientras flexionas los codos, aprieta arriba y desciende lentamente sin balancear el cuerpo.', cue: 'Solo se mueve el antebrazo: no uses impulso de hombros o espalda.' },
  { id: 'lateral', icon: '✦', title: 'ALAS DEL HUNTER', name: 'Dumbbell Lateral Raise', detail: '3 × 15 · +25 XP', xp: 115, target: 'Deltoides', secondary: ['Trapecios'], equipment: 'Mancuernas', category: 'HOMBROS', media: `${exerciseMedia}0334-DsgkuIt.gif`, instructions: 'De pie, eleva las mancuernas hacia los lados hasta que los brazos queden paralelos al suelo. Baja despacio y mantén una ligera flexión en los codos.', cue: 'Lidera con los codos y no subas por encima de los hombros.' },
  { id: 'pushup', icon: '◇', title: 'VOLUNTAD DEL SUELO', name: 'Push-up', detail: '4 × 12 · +20 XP', xp: 100, target: 'Pectorales', secondary: ['Tríceps', 'Core'], equipment: 'Peso corporal', category: 'PECHO', media: `${exerciseMedia}0662-I4hDWkc.gif`, instructions: 'Coloca las manos bajo los hombros y el cuerpo en línea recta. Baja el pecho manteniendo los codos en diagonal y empuja el suelo hasta extender los brazos.', cue: 'Aprieta glúteos y abdomen para que la cadera no se hunda.' },
  { id: 'plank', icon: '▰', title: 'NÚCLEO INQUEBRANTABLE', name: 'Plank', detail: '3 × 45 s · +20 XP', xp: 100, target: 'Abdominales', secondary: ['Hombros', 'Glúteos'], equipment: 'Peso corporal', category: 'CORE', media: `${exerciseMedia}0464-CosupLu.gif`, instructions: 'Apoya antebrazos y puntas de los pies. Forma una línea recta desde la cabeza hasta los talones y respira manteniendo el abdomen activo.', cue: 'Acerca el ombligo a la columna sin contener la respiración.' },
  { id: 'band-curl', icon: '≈', title: 'TENSIÓN ELÁSTICA', name: 'Band Alternating Biceps Curl', detail: '3 × 12 · +20 XP', xp: 105, target: 'Bíceps', secondary: ['Antebrazos'], equipment: 'Bandas', category: 'BRAZOS', media: `${exerciseMedia}0968-3omWx6P.gif`, instructions: 'Pisa el centro de la banda y toma un extremo con cada mano. Flexiona un codo por vez manteniendo el otro brazo estable y controla el regreso.', cue: 'Mantén la banda tensa abajo y evita inclinar el torso.' },
  { id: 'cable-pulldown', icon: '⌁', title: 'POLEA DEL VACÍO', name: 'Alternate Lateral Pulldown', detail: '3 × 10 · +30 XP', xp: 130, target: 'Dorsales', secondary: ['Bíceps', 'Romboides'], equipment: 'Cable', category: 'ESPALDA', media: `${exerciseMedia}0007-4IKbhHV.gif`, instructions: 'Toma el agarre de la polea con el torso estable. Lleva el codo hacia abajo y atrás hasta acercarlo al costado, luego regresa lentamente.', cue: 'Inicia cada repetición deprimiendo el hombro, no tirando con la mano.' },
  { id: 'kettlebell-press', icon: '●', title: 'PRENSA DEL MONARCA', name: 'Kettlebell Alternating Press', detail: '3 × 10 · +30 XP', xp: 135, target: 'Deltoides', secondary: ['Tríceps', 'Core'], equipment: 'Kettlebell', category: 'HOMBROS', media: `${exerciseMedia}0520-5KLbZWx.gif`, instructions: 'Sostén la kettlebell a la altura del hombro y presiónala por encima de la cabeza. Baja con control y alterna los brazos manteniendo el torso firme.', cue: 'Aprieta el abdomen y evita arquear la zona lumbar al extender.' },
];
const datasetMissions = (window.forgeDataset || []).map((exercise, index) => { const exerciseName = exercise.name || `Ejercicio ${index + 1}`; const normalizedName = exerciseName.toLowerCase(); const needsPullupBar = /pull|chin|muscle up|hanging|hang/.test(normalizedName); const equipment = needsPullupBar ? 'Barra de dominadas' : 'Peso corporal'; const mediaFile = (exercise.gif_url || '').replace(/^videos\//, ''); return { id: `dataset-${exercise.id}`, icon: needsPullupBar ? '↟' : '◇', title: exerciseName.toUpperCase(), name: exerciseName, detail: '3 × 10 · +20 XP', xp: 100 + (index % 4) * 10, target: exercise.target || 'Cuerpo completo', secondary: exercise.secondary_muscles || [], equipment, category: (exercise.category || 'PESO CORPORAL').toUpperCase(), media: mediaFile ? `${exerciseMedia}${mediaFile}` : '', instructions: exercise.instructions_es || 'Realiza el movimiento de forma controlada, manteniendo una respiración constante y una técnica segura.', cue: needsPullupBar ? 'Inicia el movimiento con los omóplatos y evita balancearte.' : 'Mantén el abdomen activo y controla tanto la subida como la bajada.' }; });
const walkingMissions = Array.from({ length: 11 }, (_, index) => { const speed = Number((1 + index * 0.5).toFixed(1)); const speedLabel = Number.isInteger(speed) ? String(speed) : speed.toFixed(1); return { id: `walk-${speedLabel.replace('.', '-')}`, icon: '↠', title: `CAMINATA ${speedLabel} KM/H`, name: 'Caminata', detail: '20 MIN · +20 XP', xp: 80 + index * 5, target: 'Sistema cardiovascular', secondary: [], equipment: 'Peso corporal', category: 'CARDIO', media: '', instructions: `Caminá durante 20 minutos manteniendo una velocidad constante de ${speedLabel} km/h. Conservá una postura erguida, apoyá el talón y balanceá los brazos de forma natural.`, cue: speed <= 2 ? 'Ritmo cómodo: podés mantener una conversación.' : speed <= 4 ? 'Ritmo activo: respiración controlada y pasos firmes.' : 'Ritmo intenso: sostené la velocidad sin correr.' }; });
const missionCatalog = [...curatedMissions, ...walkingMissions, ...datasetMissions];
const statDefaults = [
  { name: 'Pecho', value: 8, trend: '0%' }, { name: 'Espalda', value: 7, trend: '0%' }, { name: 'Piernas', value: 9, trend: '0%' },
  { name: 'Hombros', value: 6, trend: '0%' }, { name: 'Brazos', value: 8, trend: '0%' }, { name: 'Core', value: 5, trend: '0%' },
];
const equipmentOptions = [
  { id: 'Peso corporal', label: 'PESO\nCORPORAL', icon: '◇' },
  { id: 'Barra', label: 'BARRA', icon: '━' },
  { id: 'Barra de dominadas', label: 'BARRA DE\nDOMINADAS', icon: '╫' },
  { id: 'Mancuernas', label: 'MANCUERNAS', icon: '╋' },
  { id: 'Bandas', label: 'BANDAS', icon: '≈' },
  { id: 'Cable', label: 'CABLE', icon: '⌁' },
  { id: 'Kettlebell', label: 'KETTLEBELL', icon: '●' },
];
const initialStatValues = Object.fromEntries(statDefaults.map(stat => [stat.name, stat.value]));
let state = JSON.parse(localStorage.getItem('forge-state') || '{"completed":[],"completedTotal":0,"activeMissionIds":["bench","pullup","deadlift"],"nextMissionIndex":3,"equipment":["Peso corporal","Barra","Barra de dominadas","Mancuernas"],"xp":0,"sessions":0,"streak":0,"bestStreak":0,"lastActiveDate":null,"achievements":0}');
state.completedTotal = state.completedTotal || state.completed?.length || 0;
state.equipment = state.equipment?.length ? state.equipment : ['Peso corporal', 'Barra', 'Barra de dominadas', 'Mancuernas'];
state.activeMissionIds = state.activeMissionIds?.length ? state.activeMissionIds : ['bench', 'pullup', 'deadlift'];
state.nextMissionIndex = state.nextMissionIndex || 3;
state.streak = state.streak || 0;
state.bestStreak = state.bestStreak || 0;
state.lastActiveDate = state.lastActiveDate || null;
state.achievements = state.achievements || 0;
state.statValues = state.statValues || { ...initialStatValues };
function save() { localStorage.setItem('forge-state', JSON.stringify(state)); }
function getLocalDateKey(date = new Date()) { const year = date.getFullYear(); const month = String(date.getMonth() + 1).padStart(2, '0'); const day = String(date.getDate()).padStart(2, '0'); return `${year}-${month}-${day}`; }
function recordDailyActivity() { const today = getLocalDateKey(); if (!state.lastActiveDate) state.streak = 1; else if (state.lastActiveDate !== today) { const previous = new Date(`${state.lastActiveDate}T00:00:00`); const elapsedDays = Math.round((new Date(`${today}T00:00:00`) - previous) / 86400000); state.streak = elapsedDays === 1 ? state.streak + 1 : 1; } state.lastActiveDate = today; state.bestStreak = Math.max(state.bestStreak, state.streak); }
function getTier(value) { if (value >= 81) return 'S'; if (value >= 66) return 'A'; if (value >= 51) return 'B'; if (value >= 36) return 'C'; if (value >= 21) return 'D'; if (value >= 11) return 'E'; return 'F'; }
function getStats() { return statDefaults.map(stat => { const value = state.statValues[stat.name] ?? stat.value; return { ...stat, value, tier: getTier(value) }; }); }
const rankOrder = ['F', 'E', 'D', 'C', 'B', 'A', 'S'];
function getPowerScore() { return Math.round(getStats().reduce((total, stat) => total + stat.value, 0) / statDefaults.length); }
function getCurrentLevel() { return Math.floor(Math.max(0, state.xp) / 3000); }
function getMissionMinLevel(mission) { if (mission.equipment === 'Barra de dominadas') return 4; if (mission.equipment === 'Barra') return 2; if (mission.equipment === 'Mancuernas' || mission.equipment === 'Cable' || mission.equipment === 'Kettlebell' || mission.equipment === 'Bandas') return 1; const text = `${mission.name} ${mission.title}`.toLowerCase(); const walkingSpeed = mission.category === 'CARDIO' && text.match(/caminata\s+(\d+(?:\.\d+)?)\s+km\/h/); if (walkingSpeed) { const speed = Number(walkingSpeed[1]); return speed >= 5 ? 2 : speed >= 3 ? 1 : 0; } if (/muscle up|pistol|handstand|planche|dragon|one arm|burpee/.test(text)) return 2; if (/jump|climber|skater|high knee|ski step|star jump/.test(text)) return 1; return 0; }
function getMissionKind(mission) { if (/^caminata\s/.test(mission.title.toLowerCase())) return 'walking'; if (mission.category === 'CARDIO') return 'cardio'; return 'strength'; }
function getMissionRank(mission) { const minLevel = getMissionMinLevel(mission); if (minLevel >= 4) return 'C'; if (minLevel >= 2) return 'D'; if (minLevel >= 1) return 'E'; return 'F'; }
function getAllowedMissionRanks() { const currentIndex = rankOrder.indexOf(getTier(getPowerScore())); const allowed = new Set([rankOrder[currentIndex], rankOrder[Math.max(0, currentIndex - 1)]]); if (state.completedTotal % 3 === 0 && currentIndex < rankOrder.length - 1) allowed.add(rankOrder[currentIndex + 1]); return allowed; }
function getAvailableCatalog() { const level = getCurrentLevel(); const allowedRanks = getAllowedMissionRanks(); return missionCatalog.filter(mission => state.equipment.includes(mission.equipment) && getMissionMinLevel(mission) <= level && allowedRanks.has(getMissionRank(mission))); }
function getActiveMissions() { const allowedRanks = getAllowedMissionRanks(); return state.activeMissionIds.map(id => missionCatalog.find(mission => mission.id === id)).filter(mission => mission && state.equipment.includes(mission.equipment) && getMissionMinLevel(mission) <= getCurrentLevel() && allowedRanks.has(getMissionRank(mission))); }
function getNextMission() { const available = getAvailableCatalog(); const activeIds = new Set(state.activeMissionIds); const activeMissions = state.activeMissionIds.map(id => missionCatalog.find(mission => mission.id === id)).filter(Boolean); const activeKinds = new Set(activeMissions.map(getMissionKind)); const activeStats = new Set(activeMissions.map(getStatName)); const weakestStat = getStats().reduce((lowest, stat) => stat.value < lowest.value ? stat : lowest, getStats()[0]).name; const predicates = [mission => getStatName(mission) === weakestStat && !activeStats.has(getStatName(mission)), mission => !activeStats.has(getStatName(mission)) && !activeKinds.has(getMissionKind(mission)), mission => !activeStats.has(getStatName(mission)), mission => !activeKinds.has(getMissionKind(mission)), () => true]; for (const predicate of predicates) { for (let offset = 0; offset < available.length; offset += 1) { const index = (state.nextMissionIndex + offset) % available.length; const candidate = available[index]; if (!activeIds.has(candidate.id) && predicate(candidate)) { state.nextMissionIndex = (index + 1) % available.length; return candidate; } } } return available[state.nextMissionIndex++ % available.length]; }
function refreshActiveMissions() { if (!getAvailableCatalog().length) state.equipment = [...new Set([...state.equipment, 'Peso corporal'])]; const available = getAvailableCatalog(); const compatibleIds = new Set(available.map(mission => mission.id)); const availableKinds = new Set(available.map(getMissionKind)); const availableStats = new Set(available.map(getStatName)); const seenKinds = new Set(); const seenStats = new Set(); state.activeMissionIds = state.activeMissionIds.filter(id => { const mission = missionCatalog.find(candidate => candidate.id === id); if (!mission || !compatibleIds.has(id)) return false; const kind = getMissionKind(mission); const stat = getStatName(mission); if (availableKinds.size > 1 && seenKinds.has(kind)) return false; if (availableStats.size > 1 && seenStats.has(stat)) return false; seenKinds.add(kind); seenStats.add(stat); return true; }); while (state.activeMissionIds.length < Math.min(3, available.length)) { state.activeMissionIds.push(getNextMission().id); } }
function getMissionPrescription(mission) { const match = mission.detail.match(/(\d+)\s*×\s*([^·]+)/); if (!match) return mission.detail.split('·')[0].trim().toUpperCase(); const amount = match[2].trim(); const formattedAmount = /^\d+$/.test(amount) ? `${amount} REPS` : amount.toUpperCase(); return `${match[1]} SERIES · ${formattedAmount}`; }
function getMissionStatReward(mission) { const difference = rankOrder.indexOf(getMissionRank(mission)) - rankOrder.indexOf(getTier(getPowerScore())); const baseReward = difference < 0 ? 1 : difference > 0 ? 6 : 3; const stats = getStats(); const missionStat = stats.find(stat => stat.name === getStatName(mission)); const weakestValue = Math.min(...stats.map(stat => stat.value)); const balanceBonus = missionStat && missionStat.value <= weakestValue + 2 ? 1 : 0; return baseReward + balanceBonus; }
function renderMission(mission) { return `<article class="mission-card"><div class="mission-icon">${mission.icon}</div><div><div class="mission-title">${mission.title}<span class="mission-prescription">${getMissionPrescription(mission)}</span></div><div class="mission-meta">${mission.name} · ${mission.equipment} · RANGO ${getMissionRank(mission)}</div><button class="mission-info" data-info="${mission.id}">VER EJERCICIO · RANGO ${getMissionRank(mission)} →</button></div><div class="mission-xp"><span>+${mission.xp} XP</span><small class="mission-stats">${getStatName(mission).toUpperCase()} +${getMissionStatReward(mission)}</small><button class="mission-action" data-mission="${mission.id}">COMPLETAR</button></div></article>`; }
function getStatName(mission) { const primary = `${mission.category} ${mission.target}`.toLowerCase(); const secondary = mission.secondary.join(' ').toLowerCase(); if (/chest|pector|pecho/.test(primary)) return 'Pecho'; if (/back|lat|espalda|rhomboid/.test(primary)) return 'Espalda'; if (/leg|quad|glute|hamstring|calf|pierna|glúteo/.test(primary)) return 'Piernas'; if (/shoulder|delt|hombro|trap/.test(primary)) return 'Hombros'; if (/arm|bicep|tricep|forearm|brazo|bícep|trícep/.test(primary)) return 'Brazos'; if (/chest|pector|pecho/.test(secondary)) return 'Pecho'; if (/back|lat|espalda|rhomboid/.test(secondary)) return 'Espalda'; if (/leg|quad|glute|hamstring|calf|pierna|glúteo/.test(secondary)) return 'Piernas'; if (/shoulder|delt|hombro|trap/.test(secondary)) return 'Hombros'; if (/arm|bicep|tricep|forearm|brazo|bícep|trícep/.test(secondary)) return 'Brazos'; return 'Core'; }
function updateStatsForMission(mission, reward) { const statName = getStatName(mission); state.statValues[statName] = Math.min(100, state.statValues[statName] + reward); }
function renderStats() { const stats = getStats(); const powerScore = Math.round(stats.reduce((total, stat) => total + stat.value, 0) / stats.length); const weakest = stats.reduce((lowest, stat) => stat.value < lowest.value ? stat : lowest, stats[0]); document.querySelector('#statGrid').innerHTML = stats.slice(0, 3).map(s => `<div class="stat-card"><span>${s.name.toUpperCase()}</span><strong>${s.value}</strong><small>RANGO ${s.tier}</small></div>`).join(''); document.querySelector('#statDetailList').innerHTML = stats.map(s => `<div class="detail-row"><div class="detail-line"><strong>${s.name}</strong><span>${s.value}% · ${s.tier}</span></div><div class="bar-line"><span style="width:${s.value}%"></span></div><small>+${s.trend} esta semana</small></div>`).join(''); document.querySelector('#powerScore').textContent = powerScore; document.querySelector('#scoreRing').textContent = `${powerScore}%`; document.querySelector('#weaknessText').textContent = `${weakest.name} está en fase inicial. Completá misiones para subirlo.`; }
function renderEquipment() { document.querySelector('#equipmentGrid').innerHTML = equipmentOptions.map(option => `<button class="equipment-option ${state.equipment.includes(option.id) ? 'selected' : ''}" data-equipment="${option.id}" aria-pressed="${state.equipment.includes(option.id)}"><span class="equipment-icon">${option.icon}</span><span>${option.label.replace('\n', '<br />')}</span><b>${state.equipment.includes(option.id) ? '✓' : ''}</b></button>`).join(''); document.querySelector('#equipmentCount').textContent = `${String(state.equipment.length).padStart(2, '0')} ACTIVOS`; }
function render() { refreshActiveMissions(); const activeMissions = getActiveMissions(); document.querySelector('#missionList').innerHTML = activeMissions.map(renderMission).join(''); document.querySelector('#fullMissionList').innerHTML = activeMissions.map(renderMission).join(''); renderStats(); renderEquipment(); document.querySelector('#missionCounter').textContent = `${String(state.completedTotal).padStart(2,'0')} / ∞`; const xp = Math.max(0, state.xp); const level = getCurrentLevel(); const levelXp = xp % 3000; const powerScore = getPowerScore(); document.querySelector('#levelLabel').textContent = `LVL ${level}`; document.querySelector('#profileLevel').textContent = level; document.querySelector('#totalXp').textContent = xp.toLocaleString('es-AR'); document.querySelector('#sessionCount').textContent = state.sessions; document.querySelector('#bestStreak').textContent = `${state.bestStreak}d`; document.querySelector('#achievementCount').textContent = state.achievements; document.querySelector('#streakLabel').textContent = state.streak ? `🔥 ${state.streak} DÍAS` : '0 DÍAS'; document.querySelector('#xpLabel').textContent = `${levelXp.toLocaleString('es-AR')} / 3.000 XP`; document.querySelector('#xpToNextLabel').textContent = `+${(3000 - levelXp).toLocaleString('es-AR')} XP para ascender`; document.querySelector('#xpBar').style.width = `${Math.min(100, (levelXp / 3000) * 100)}%`; document.querySelector('#rankName').textContent = level >= 13 ? 'MONARCH AWAKENED' : level >= 4 ? 'SHADOW RUNNER' : 'AWAKENING'; document.querySelector('#profileRank').textContent = `RANGO ${getTier(powerScore)}`; }
function openExercise(id) { const mission = missionCatalog.find(item => item.id === id); if (!mission) return; document.querySelector('#modalMedia').src = mission.media; document.querySelector('#modalMedia').onerror = () => { document.querySelector('#modalMedia').classList.add('media-missing'); }; document.querySelector('#modalCategory').textContent = `${mission.category} · ${mission.name}`; document.querySelector('#modalTitle').textContent = mission.title; document.querySelector('#modalPrescription').textContent = getMissionPrescription(mission); document.querySelector('#modalTags').innerHTML = [`${getStatName(mission).toUpperCase()} +${getMissionStatReward(mission)}`].map(tag => `<span>${tag}</span>`).join(''); document.querySelector('#modalInstructions').textContent = mission.instructions; document.querySelector('#modalCue').textContent = mission.cue; document.querySelector('#modalComplete').dataset.mission = mission.id; document.querySelector('#exerciseModal').classList.add('open'); document.querySelector('#exerciseModal').setAttribute('aria-hidden', 'false'); }
function closeExercise() { document.querySelector('#exerciseModal').classList.remove('open'); document.querySelector('#exerciseModal').setAttribute('aria-hidden', 'true'); }
function completeMission(id) { const mission = missionCatalog.find(item => item.id === id); if (!mission || !state.activeMissionIds.includes(id)) return; const statReward = getMissionStatReward(mission); state.activeMissionIds = state.activeMissionIds.filter(activeId => activeId !== id); state.activeMissionIds.push(getNextMission().id); state.completedTotal += 1; state.xp += mission.xp; state.sessions += 1; recordDailyActivity(); state.achievements = Math.floor(state.completedTotal / 3); updateStatsForMission(mission, statReward); save(); render(); closeExercise(); showToast(`MISIÓN COMPLETADA  +${mission.xp} XP · +${statReward} STAT`); }
function showToast(text) { const toast = document.querySelector('#toast'); toast.textContent = text; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2200); }
document.addEventListener('click', e => { const nav = e.target.closest('[data-screen]'); if (nav) { document.querySelectorAll('.screen').forEach(s => s.classList.toggle('active', s.id === nav.dataset.screen)); document.querySelectorAll('.nav-item').forEach(n => n.classList.toggle('active', n.dataset.screen === nav.dataset.screen)); window.scrollTo({ top: 0, behavior: 'smooth' }); } const info = e.target.closest('[data-info]'); if (info) openExercise(info.dataset.info); const action = e.target.closest('[data-mission]'); if (action) completeMission(action.dataset.mission); const equipment = e.target.closest('[data-equipment]'); if (equipment) { const id = equipment.dataset.equipment; const nextEquipment = state.equipment.includes(id) ? state.equipment.filter(item => item !== id) : [...state.equipment, id]; const hasValidMission = missionCatalog.some(mission => nextEquipment.includes(mission.equipment) && getMissionMinLevel(mission) <= getCurrentLevel()); if (!hasValidMission) { showToast('NECESITÁS PESO CORPORAL PARA ESTE NIVEL'); return; } state.equipment = nextEquipment; refreshActiveMissions(); save(); render(); showToast(`EQUIPAMIENTO ACTUALIZADO · ${state.equipment.length} ACTIVOS`); } if (e.target.closest('[data-close-modal]')) closeExercise(); });
document.querySelector('#modalComplete').addEventListener('click', e => completeMission(e.currentTarget.dataset.mission));
document.querySelector('#resetButton').addEventListener('click', () => { if (confirm('¿Reiniciar todo tu progreso local?')) { state = { completed: [], completedTotal: 0, activeMissionIds: ['bench', 'pullup', 'deadlift'], nextMissionIndex: 3, equipment: ['Peso corporal', 'Barra', 'Barra de dominadas', 'Mancuernas'], xp: 0, sessions: 0, streak: 0, bestStreak: 0, lastActiveDate: null, achievements: 0, statValues: { ...initialStatValues } }; save(); render(); showToast('PROTOCOLO RESTAURADO · 0 XP'); } });
render();